services:
  crowdwalk:
    build:
      context: .
      dockerfile: Dockerfile
    image: crowdwalk:latest
    container_name: crowdwalk
    working_dir: /CrowdWalk/crowdwalk
    environment:
      - LANG=ja_JP.UTF-8
      - JAVA_OPTS=-Dgroovy.source.encoding=UTF-8 -Dfile.encoding=UTF-8
    tty: true
    stdin_open: true
    volumes:
      - ./.gradle:/root/.gradle
